### ISSUE TITLE
Instant replay keeps enabling/disabling when watching Netflix and input language changes?

### ISSUE THREAD

**Issue by xPokerr** [Verpous/AlwaysShadow#1]
I've added both Netflix processes to the "Whitelist.txt" file but AlwaysShadow keeps trying to enable Instant Replay when watching Netflix and keeps changing my input language to English instead of keeping default language.

**Comment by Verpous** [comment]
For the whitelist issue, it's hard for me to help you but I can ask you to verify that the line for the Netflix process in your whitelist matches its command line according to what you see in Task Manager exactly. Also, make sure that you restart AlwaysShadow after modifying the whitelist. I can also tell you that I didn't need to add more than one process to my list to block Netflix, even though Netflix does run several process, so maybe you just need to find the right one. If this issue only happens to you rarely and not every time you run Netflix, then you can manually disable AlwaysShadow when it happens.

As for the language switch, it happened to me too and it's because the default shortcut for toggling Shadowplay is Alt+Shift+F10 which contains Alt+Shift which changes languages. I solved this by changing the shortcut to toggle Shadowplay (I use Ctrl+Shift+F10). Make sure to restart AlwaysShadow after changing the shortcut.

**Comment by rhipex** [comment]
Hi, I was not able to get it to work, until I realized that you need to have a shortcut set for instant replay on/off. I had the shortcut disabled and it was not working. After I set it to Ctrl+Shift+F10 it started working. Thank you!

**Comment by AvivEdery** [comment]
@benedlore I don't have ideas for solving your problem, sorry.

**Comment by jonymer** [comment]
@AvivEdery damn I was hoping this program could solve this issue with having crunchyroll or netflix in the background.

**Comment by ttactivau** [comment]
Whitelist for Netflix does not work, need help to solve it please.
All I need to do is just to inicialize executable and drag the Whitelist.txt file ?

**Comment by PolicyPuma4** [comment]
> For the whitelist issue, it's hard for me to help you but I can ask you to verify that the line for the Netflix process in your whitelist matches its command line according to what you see in Task Manager exactly. Also, make sure that you restart AlwaysShadow after modifying the whitelist. I can also tell you that I didn't need to add more than one process to my list to block Netflix, even though Netflix does run several process, so maybe you just need to find the right one. If this issue only happens to you rarely and not every time you run Netflix, then you can manually disable AlwaysShadow when it happens.
> 
> As for the language switch, it happened to me too and it's because the default shortcut for toggling Shadowplay is Alt+Shift+F10 which contains Alt+Shift which changes languages. I solved this by changing the shortcut to toggle Shadowplay (I use Ctrl+Shift+F10). Make sure to restart AlwaysShadow after changing the shortcut.

FYI ShadowPlay has a local webserver running which can be used to do a plethera of things, including getting and setting the current Instant Replay state. [@cm_pony](https://github.com/cm-pony) explains [here](https://github.com/cm-pony/Experienceless/issues/1#issuecomment-763496808). I'd imagine this would be a more reliable way to fetch and post the Instant Replay state.

**Comment by PolicyPuma4** [comment]
For anyone experiencing this issue still, I've gone ahead and created [`PersistentInstant`](https://github.com/PolicyPuma4/PersistentInstant), a teeny tiny app that does exactly what [`AlwaysShadow`](https://github.com/Verpous/AlwaysShadow) does, however it doesn't rely on using hotkeys to enable Instant Replay, so it will not change your input language or trigger any other hotkeys.

If you still experience the Netflix issue on [`PersistentInstant`](https://github.com/PolicyPuma4/PersistentInstant), do let me know and I'll investigate further.

**Comment by Verpous** [comment]
@PolicyPuma4 Looks like I've got competition! Thanks for the resources, maybe I'll change AlwaysShadow to use it sometime. It's just a little outside my comfort zone so I will need to find a time when I feel like learning it.

**Comment by PolicyPuma4** [comment]
> 

To enable Instant Replay via the HTTP API, you must send a POST request to `http://localhost:<port>/ShadowPlay/v.1.0/InstantReplay/Enable` with a header `X_LOCAL_SECURITY_COOKIE` set as `<secret>` and the body set as `{"status":true}`. `<port>` and `<secret>` are both located in a memory mapped file which ShadowPlay creates.

While making a HTTP request in C is no trivial task, and I haven't taken on that challenge just yet, with my couple hours of learning C, I have managed to extract the `<port>` and `<secret>` from the memory mapped file.

<details>

```c
#include <stdio.h>

#include <windows.h>

void substr(char *dest, char *source, int start, int length)
{
    memcpy(dest, source + start, length);
    dest[length] = '\0';
}

int main() {
    HANDLE mapHandle = OpenFileMapping(FILE_MAP_READ, FALSE, "{8BA1E16C-FC54-4595-9782-E370A5FBE8DA}");
    if (mapHandle == NULL)
    {
        return 1;
    }

    LPVOID mapView = MapViewOfFile(mapHandle, FILE_MAP_READ, 0, 0, 0);
    if (mapView == NULL)
    {
        CloseHandle(mapHandle);
        return 1;
    }

    char *pMapping = (char *)mapView;
    if (strlen(pMapping) != 58)
    {
        return 1;
    }
    char str[strlen(pMapping) + 1];
    strcpy(str, pMapping);

    UnmapViewOfFile(mapView);
    CloseHandle(mapHandle);

    char port[5 + 1];
    substr(port, str, 8, 5);
    char secret[32 + 1];
    substr(secret, str, 24, 32);
    printf("%s, %s\n", port, secret);

    return 0;
}
```
</details>

**Comment by Verpous** [comment]
@PolicyPuma4 I just released a new version which uses this method, using libcurl to do some heavy lifting. Thanks!
