### ISSUE TITLE
Request for Disable and Stop

### ISSUE THREAD

**Issue by brunoherrera** [Verpous/AlwaysShadow#10]
can you please add an extra option to also Stop shadowplay? we have the "Disable until I turn it back on" but it would be nice to also have a "Disable and Stop until I turn it back on", I often have to open nvidia overlay and stop it manually after I use "Disable until I turn it back on"

**Comment by brunoherrera** [comment]
hmmm, coincidentally I changed recordings and temp folder and it seems to stop when I disable, maybe it was just a bug, feel free to close the issue if you think so

**Comment by Verpous** [comment]
Disable doesn't currently also stop Shadowplay, if you encountered a bug it's only that AlwaysShadow requires a restart after changing the temp folder location on older versions. I will take this feature under consideration

**Comment by brunoherrera** [comment]
@Verpous love the new update bro! thanks!!! ♥
