### ISSUE TITLE
Doesnt start at startup

### ISSUE THREAD

**Issue by Gvasi** [Verpous/AlwaysShadow#12]
I have the app for a few months now without an issue, but for some reason the last few days the app doesnt start when i restart my computer. I try delete it re enable startup apps, add shortcut to start app folder but nothing. The app is showing normally on the start up as enabled but it doesnt start

**Comment by Verpous** [comment]
Instead of using the startup apps menu in Windows settings, try manually creating a shortcut to AlwaysShadow in the startup like in [this guide](https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd).

Maybe I'll add a built-in feature to add AlwaysShadow to startup in the future.

**Comment by Gvasi** [comment]
Hey thanks for your quick reply
I tried this I also delete it restart and put it again but still nothing.

The app if I Open it manually works perfectly and I didn't had any issue some months now but today after I restart my PC I noticed the issue.

I have window 11 and I'm in the beta channel if that helps.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Verpous** [comment]
Can you try putting another program there, any program doesn't matter which, just to see if the problem is exclusive to AlwaysShadow?

**Comment by Gvasi** [comment]
Good morning, just tried it if I put any other programs it starts normally.

I start to think if this is a issue with Nvidia broadcast? That also lunch on startup or maybe the antivirus? I check settings and everything and doesn't seems to interact with it in anyway I'm just saying random thoughts....the issue is slesific for the always shadow

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Verpous** [comment]
Try this:

1. Exit AlwaysShadow (right click on the tray icon -> Exit)
2. Go to `%LOCALAPPDATA%/AlwaysShadow/`
3. Delete the file `output.log` there
4. Restart your computer
5. See if `output.log` was created there again. If it's there, send it to me here

**Comment by Gvasi** [comment]
Thanks that seems to fix it
Thank you for your quick reply and help

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Verpous** [comment]
That wasn't meant to fix anything, it was only meant to help troubleshoot 😅 But glad to be of service
