### ISSUE TITLE
Question, does AlwaysShadow work with udemy or netflix open in a Browser?

### ISSUE THREAD

**Issue by Amueller36** [Verpous/AlwaysShadow#13]
I am a student and I often like to play games in between my study sessions and keep my browser open when listening to music etc.
But Shadowplay wont let me save the instant replay when I have DRM Content open in the Background.

Does AlwaysShadow allow me to still record it?

![image](https://github.com/Verpous/AlwaysShadow/assets/102921542/3f9e5def-6285-42b9-b818-569939a8c215)
As you can see, the save button is greyed out if I have udemy open

**Comment by Verpous** [comment]
Sadly, the best you can do when a conflicting program insists on disabling Shadowplay is to let it win by whitelisting it.
