### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by brunoherrera** [Verpous/AlwaysShadow#14]
Hi, I don't care about this so much because I have a lot of ram to spare, but I'm dropping this screenshot here in case there is an actual issue with it, it happens after a few days (I leave my pc on 24/7 and only reboot if needed) so pay attention to "Started:" field in the screenshot too (4 days 1 hour) and 7.84GB of ram usage (7.85GB as I'm writing this)

![Screenshot 2024-02-26 223311](https://github.com/Verpous/AlwaysShadow/assets/32912794/82620dde-c6b0-4727-a229-953e961a87d3)

**Comment by brunoherrera** [comment]
7.96GB right now, so we can have an idea of the rate it's going up

**Comment by Verpous** [comment]
Oh my, you're absolutely right. I found the leak and fixed it in the latest release which already up. As it happens I already had a few changes that I was about to release soon anyway, so you get all of those a bit early because of this. Thanks!
