### ISSUE TITLE
Processes with no commandline

### ISSUE THREAD

**Issue by i1u5** [Verpous/AlwaysShadow#15]
Hi, would there be any way to make it specifically work with the process filename instead of the commandline? Some games seem to intentionally not use a commandline. Maybe add a new expression specifically for it, something like:
`??EP Process.exe`

Example: (using `wmic path win32_process get name,commandline`, the process I'm referring to in this case is `VALORANT-Win64-Shipping.exe`)
![image](https://github.com/Verpous/AlwaysShadow/assets/26717942/e70f5952-4698-4eda-b3d9-9c02babc13c9)

**Comment by Verpous** [comment]
Sounds simple enough so I'll probably add it but since I just published a release I don't know to tell you when the next one will be.

**Comment by i1u5** [comment]
> Sounds simple enough so I'll probably add it but since I just published a release I don't know to tell you when the next one will be.

Sure take your time, thanks for this great tool.

**Comment by i1u5** [comment]
> @i1u5 Hey there, this feature is now included in the latest release. Enjoy!

Thanks man I appreciate the effort!
