### ISSUE TITLE
Mouse aim feels off and NVIDIA overlay is glitchy when using this program

### ISSUE THREAD

**Issue by washurpaws** [Verpous/AlwaysShadow#17]
I downloaded this again, and i'm unsure what is going on, but whenever I use AlwaysShadow there's a very noticeable mouse issue, where at some points the sensitivity kind of slows down, before speeding back up.  Also, sometimes when I go to the settings overlay while in-game, my mouse barely works and the thing is glitching out like crazy. This only started happening once I started using this app, so I assume that's causing it. Tried an old version (that I know used to work perfectly without problems) and it happened there too... Maybe it's a bug in the game i'm playing (CoD MW2) or something else wrong with my system? I don't really know, but making this bug report in hopes that this can be fixed.

I'm on Windows 11 (worked fine on W10, could be that?) and have a 1070ti. Please tell me if there's any other info that I could give that could help solve this bug.

**Comment by Verpous** [comment]
Sounds bizarre, I don't know what my program does that could possibly cause this. But we can try. For starters please refresh/exit AlwaysShadow then drop the log file located at `%LOCALAPPDATA%/AlwaysShadow/output.log`

Does this happen with other games, and does this happen when AlwaysShadow isn't running?

**Comment by washurpaws** [comment]
Hm, after doing some further testing (aka just disabling/enabling stuff and seeing what happens), it seems like it might just be the game bugging out when shadowplay is enabled? very strange, wonder if it's the new nvidia app or something.

Here's the latest run in the output log:

`~~~~ STARTING A RUN: BUILD DATE Feb 27 2024 15:23:49 ~~~~

[INF] 2024-05-19 12:40:34 main.c:InitializeCwd:272: Successfully set CWD to C:\Users\kira\Documents
[INF] 2024-05-19 12:40:34 main.c:AddNotificationIcon:595: Notification icon successfully created.
[INF] 2024-05-19 12:40:34 main.c:IsUpdatesSquelched:766: Updates are not squelched because registry key doesn't exist
[INF] 2024-05-19 12:40:34 fixer.c:FetchToggleShortcut:380: Shortcut length: 3
[INF] 2024-05-19 12:40:34 fixer.c:FetchToggleShortcut:408: Adding vkey 0x12 to shortcut.
[INF] 2024-05-19 12:40:34 fixer.c:FetchToggleShortcut:408: Adding vkey 0x10 to shortcut.
[INF] 2024-05-19 12:40:34 fixer.c:FetchToggleShortcut:408: Adding vkey 0x79 to shortcut.
[WRN] 2024-05-19 12:40:34 fixer.c:FetchWhitelist:498: Couldn't open whitelist with error: No such file or directory.
[WRN] 2024-05-19 12:40:34 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[INF] 2024-05-19 12:40:34 main.c:IsUpdateExists:860: Latest tag: 'v1.6' EQUALS preexisting tag: 'v1.6'
[INF] 2024-05-19 12:40:34 main.c:IsUpdateExists:865: Latest tag: 'v1.6' DOESN'T EQUAL preexisting tag: 'v1.5'
[INF] 2024-05-19 12:40:34 main.c:IsUpdateExists:865: Latest tag: 'v1.6' DOESN'T EQUAL preexisting tag: 'v1.4'
[INF] 2024-05-19 12:40:34 main.c:IsUpdateExists:865: Latest tag: 'v1.6' DOESN'T EQUAL preexisting tag: 'v1.3'
[INF] 2024-05-19 12:40:34 main.c:IsUpdateExists:865: Latest tag: 'v1.6' DOESN'T EQUAL preexisting tag: 'v1.2'
[INF] 2024-05-19 12:40:34 main.c:IsUpdateExists:865: Latest tag: 'v1.6' DOESN'T EQUAL preexisting tag: 'v1.1'
[INF] 2024-05-19 12:40:34 main.c:IsUpdateExists:865: Latest tag: 'v1.6' DOESN'T EQUAL preexisting tag: 'v1.0'
[INF] 2024-05-19 12:40:34 main.c:IsUpdateExists:871: Update exists: 0
[INF] 2024-05-19 12:40:44 fixer.c:FixerLoop:125: Toggling because: isInstantReplayOn 0, isExclusiveExists 0, isExclusiveRunning 0
[WRN] 2024-05-19 12:40:44 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[WRN] 2024-05-19 12:40:44 fixer.c:SetInstantReplayByPostRequest:333: Failed to set state: 1 because the handle info couldn't be fetched
[INF] 2024-05-19 12:49:34 fixer.c:FixerLoop:125: Toggling because: isInstantReplayOn 0, isExclusiveExists 0, isExclusiveRunning 0
[WRN] 2024-05-19 12:49:34 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[WRN] 2024-05-19 12:49:34 fixer.c:SetInstantReplayByPostRequest:333: Failed to set state: 1 because the handle info couldn't be fetched
[INF] 2024-05-19 12:52:15 fixer.c:FixerLoop:125: Toggling because: isInstantReplayOn 0, isExclusiveExists 0, isExclusiveRunning 0
[WRN] 2024-05-19 12:52:15 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[WRN] 2024-05-19 12:52:15 fixer.c:SetInstantReplayByPostRequest:333: Failed to set state: 1 because the handle info couldn't be fetched
[INF] 2024-05-19 12:53:05 fixer.c:FixerLoop:125: Toggling because: isInstantReplayOn 0, isExclusiveExists 0, isExclusiveRunning 0
[WRN] 2024-05-19 12:53:05 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[WRN] 2024-05-19 12:53:05 fixer.c:SetInstantReplayByPostRequest:333: Failed to set state: 1 because the handle info couldn't be fetched
[INF] 2024-05-19 12:53:45 fixer.c:FixerLoop:125: Toggling because: isInstantReplayOn 0, isExclusiveExists 0, isExclusiveRunning 0
[WRN] 2024-05-19 12:53:45 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[WRN] 2024-05-19 12:53:45 fixer.c:SetInstantReplayByPostRequest:333: Failed to set state: 1 because the handle info couldn't be fetched
[INF] 2024-05-19 12:54:45 fixer.c:FixerLoop:125: Toggling because: isInstantReplayOn 0, isExclusiveExists 0, isExclusiveRunning 0
[WRN] 2024-05-19 12:54:45 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[WRN] 2024-05-19 12:54:45 fixer.c:SetInstantReplayByPostRequest:333: Failed to set state: 1 because the handle info couldn't be fetched
[INF] 2024-05-19 12:55:35 fixer.c:FixerLoop:125: Toggling because: isInstantReplayOn 0, isExclusiveExists 0, isExclusiveRunning 0
[WRN] 2024-05-19 12:55:35 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[WRN] 2024-05-19 12:55:35 fixer.c:SetInstantReplayByPostRequest:333: Failed to set state: 1 because the handle info couldn't be fetched
[INF] 2024-05-19 12:56:35 fixer.c:FixerLoop:125: Toggling because: isInstantReplayOn 0, isExclusiveExists 0, isExclusiveRunning 0
[WRN] 2024-05-19 12:56:35 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[WRN] 2024-05-19 12:56:35 fixer.c:SetInstantReplayByPostRequest:333: Failed to set state: 1 because the handle info couldn't be fetched
[INF] 2024-05-19 12:58:05 fixer.c:FixerLoop:125: Toggling because: isInstantReplayOn 0, isExclusiveExists 0, isExclusiveRunning 0
[WRN] 2024-05-19 12:58:05 fixer.c:FetchServerInfo:256: Failed to open the file with the port and secret, error code: 0x2
[WRN] 2024-05-19 12:58:05 fixer.c:SetInstantReplayByPostRequest:333: Failed to set state: 1 because the handle info couldn't be fetched
[INF] 2024-05-19 13:00:02 main.c:ProcessMainWindowCommand:497: Exit button has been pressed. Quitting.
[INF] 2024-05-19 13:00:02 main.c:MainWindowProcedure:424: Received WM_DESTROY. Quitting.
`

It's outputting a few errors, though considering this specific bug happens even with AlwaysShadow turned off I'm guessing it's unrelated to your program and just a general Shadowplay issue...

**Comment by Verpous** [comment]
Oh no, this is the first time I'm hearing of this new nvidia app and it sounds like I will have work to do! Those logs do indicate that shadowplay no longer works exactly the way this program expects. For now I can't make promises about anything working correctly on the new nvidia app. Anyway it sounds like your issue is not even caused by this program. Not sure what else I can do for you.

**Comment by washurpaws** [comment]
yea, it's probably not your program causing it, so my bad for wasting your time, and thanks for creating a great app :D have a great day :)
