### ISSUE TITLE
Getting an error when launching

### ISSUE THREAD

**Issue by OneManWill-ie** [Verpous/AlwaysShadow#19]
The error is : "Error creating the system tray icon. Quitting" 

![image](https://github.com/Verpous/AlwaysShadow/assets/63563160/1f1aca1f-2237-403d-9ef5-2f7e00cd56db)

I have checked and it's not already running, Just started happening today, I downloaded the most recent version and tried again but had the same issue.

Downloaded version 1.5 and 1.6 and both worked so I think it's an issue with v1.666.

**Comment by Verpous** [comment]
Uh oh. Please after this issue happens, take the log file located at `%LOCALAPPDATA%/AlwaysShadow/output.log` and drop it here

**Comment by Verpous** [comment]
Those logs don't make sense, I don't think they're from a run where you encountered this error. Please reproduce the issue again and then drop the entire log file here.
