### ISSUE TITLE
"Disable for an hour" feature

### ISSUE THREAD

**Issue by VapidLinus** [Verpous/AlwaysShadow#2]
When I'm watching Netflix, the "Shadowplay has been disabled" message shows up over and over again. So I disable AlwaysShadow but then usually forget to turn it on again.

I would love for AlwaysShadow to have an "Disable for an hour" option so I don't forget to re-enable it again.

Similar to what Flux has:
![image](https://user-images.githubusercontent.com/4418470/149236519-70958be1-afbf-4a35-abab-ad7339aca686.png)

**Comment by Verpous** [comment]
This is a good idea. I'll probably add it.

**Comment by Verpous** [comment]
This is now available in [v1.1](https://github.com/Verpous/AlwaysShadow/releases). Here's what it looks like:

![Screenshot (129)](https://user-images.githubusercontent.com/30209851/151548587-e1ddb03f-a02b-46f0-8c7d-8b18afcd15d4.png)

**Comment by VapidLinus** [comment]
That's amazing, thank you! ❤
