### ISSUE TITLE
Instant replay stuck in infinite on/off loop

### ISSUE THREAD

**Issue by lookacoyote** [Verpous/AlwaysShadow#3]
Directly after a fresh restart AlwaysShadow will enable Instant Replay and seconds later Instant Replay will be turned off. I have desktop privacy turned off- so i don't think thats the issue. Any reason why this would be happening?

**Comment by Verpous** [comment]
Maybe you have some program that disables Shadowplay set to launch on startup? If I had to guess, I heard that Spotify does this.

**Comment by Vorcikle** [comment]
I'm getting the same issue, I think it may be related to discord. When I was in a voice channel every time it would do the loop of turning off and on instant replay, I would hear the discord push to talk key sound when in a channel.

**Comment by lookacoyote** [comment]
without knowing which exact program that's causing it- i was able to stop shadowplay turning on and off by enabling desktop recording in the privacy settings. i'd rather not, but i like knowing that shadowplay is working more.  hopefully it gets figured out. thanks so much for your work on this

**Comment by Vorcikle** [comment]
I had desktop recording off, with the loop occurring. For now I will wait to use this program until this is fixed.

**Comment by Verpous** [comment]
@lookacoyote @Syanez133 I just released [v1.3](https://github.com/Verpous/AlwaysShadow/releases), where it now works correctly even when desktop capture is off.
