### ISSUE TITLE
Windows defender detects trojan

### ISSUE THREAD

**Issue by NU0VA** [Verpous/AlwaysShadow#4]
Trojan:Script/Wacatac.B!ml

**Comment by Verpous** [comment]
A bit of googling indicates this is probably a false positive and it happens sometimes with the compiler that I used. Windows Defender doesn't detect anything for me. So I don't really know what I should do about this, if anything. You can inspect the source code and compile it yourself if you'd like. Or you can tell Windows Defender to ignore this, if you trust me (and the compiler).

I'd be interested to hear if anyone else is experiencing this.

**Comment by NU0VA** [comment]
> A bit of googling indicates this is probably a false positive and it happens sometimes with the compiler that I used. Windows Defender doesn't detect anything for me. So I don't really know what I should do about this, if anything. You can inspect the source code and compile it yourself if you'd like. Or you can tell Windows Defender to ignore this, if you trust me (and the compiler).
> 
> I'd be interested to hear if anyone else is experiencing this.

**Comment by NU0VA** [comment]
Yeah I've ran the file through a couple of other virus checkers and it came out clean. The weird thing is that windows defender only tags the zip as a malicious file but the actual exe is clean.
