### ISSUE TITLE
The application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by hemantgogia09** [Verpous/AlwaysShadow#5]
I have been getting this when I try to run AlwaysShadow.exe. Quick google tells me it is something related to  .NET framework or directx setup but I verified I have everything installed. Any help will be appreciated.

**Comment by Verpous** [comment]
I may have messed something up. Go ahead and try downloading again same as you did before and tell me if it's still happening.

**Comment by hemantgogia09** [comment]
perfect it worked thanks @Verpous
