### ISSUE TITLE
Request for adding a reverse whitelist

### ISSUE THREAD

**Issue by LeeseTheFox** [Verpous/AlwaysShadow#9]
For example, I want ShadowPlay to only run when I open CSGO.exe and turn off when I close it. It will help save up resources for those, who doesn't use it outside of one game.

**Comment by Verpous** [comment]
Sounds simple enough, stay tuned

**Comment by brunoherrera** [comment]
love it! this is a great feature!

**Comment by PolicyPuma4** [comment]
I've just added this functionality to [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant).

**Steps to get started:**
1. [Download](https://github.com/PolicyPuma4/PersistentInstant/releases/latest/download/PersistentInstant_Unicode_64.exe) and install [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant)
2. Using the tray menu select edit allow list
4. Add the full path or path of the folder of any executables you want to explicitly record, separated by a newline
5. Exit [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant) using the tray menu
6. Open [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant) using the Start Menu shortcut

**Comment by brunoherrera** [comment]
> I've just added this functionality to [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant).
> 
> **Steps to get started:**
> 
> 1. [Download](https://github.com/PolicyPuma4/PersistentInstant/releases/latest/download/PersistentInstant_Unicode_64.exe) and install [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant)
> 2. Using the tray menu select edit allow list
> 3. Add the full path or path of the folder of any executables you want to explicitly record, separated by a newline
> 4. Exit [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant) using the tray menu
> 5. Open [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant) using the Start Menu shortcut

yeah right, https://www.virustotal.com/gui/file/a2cbe13ac60980904fb78259b875fbb6ac60652031f817900beffde7c9769c3a

**Comment by PolicyPuma4** [comment]
> > I've just added this functionality to [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant).
> > **Steps to get started:**
> > 
> > 1. [Download](https://github.com/PolicyPuma4/PersistentInstant/releases/latest/download/PersistentInstant_Unicode_64.exe) and install [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant)
> > 2. Using the tray menu select edit allow list
> > 3. Add the full path or path of the folder of any executables you want to explicitly record, separated by a newline
> > 4. Exit [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant) using the tray menu
> > 5. Open [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant) using the Start Menu shortcut
> 
> yeah right, https://www.virustotal.com/gui/file/a2cbe13ac60980904fb78259b875fbb6ac60652031f817900beffde7c9769c3a

Strange, both [PersistentInstant](https://github.com/PolicyPuma4/PersistentInstant) and [AutoHotkey](https://github.com/AutoHotkey/AutoHotkey) are open source, feel free to download [AutoHotkey v2.0](https://www.autohotkey.com/download/ahk-v2.exe) and build PersistentInstant from source, it should result in an identical binary, you can even read the AutoHotkey code in the binary itself by scrolling all the way to the bottom of it in a text editor.

I assume due to AutoHotkey v2.0 and that particular version of PersistentInstant being relatively new, a few engines are falsely flagging the executable as malware.

**Comment by Verpous** [comment]
@LeeseTheFox @brunoherrera I just released a new version with lots of changes including this feature. Check out the latest release.

**Comment by LeeseTheFox** [comment]
> @LeeseTheFox @brunoherrera I just released a new version with lots of changes including this feature. Check out the latest release.

Great, thanks!
I guess the next step is the simplification of this whole process, and maybe a basic app UI?

**Comment by Verpous** [comment]
@LeeseTheFox Makes sense but I wouldn't hold my breath.

**Comment by brunoherrera** [comment]
Thanks @Verpous that's epic! I'll try it later, [I scanned it in virustotal](https://www.virustotal.com/gui/file/3ac00056f4027de11f4139896a50d5f37335b94a121871a5e53f705eab84e9e2/detection)
I submitted the file to microsoft for incorrect detection to see what they say, I'm ok with the other 2 detections in virus total, but the microsoft one scares me more even though I'm sure it's just a false positive too.
